version: 1

update_configs:
  - package_manager: javascript
    directory: "/"
    update_schedule: live
    default_labels:
      - dependencies
      - javascript
    default_reviewers:
      - goodevilgenius
    target_branch: develop
